apiVersion : networking.k8s.io/v1beta1
kind: ingress
metadata:
  name: diabetesingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: diabetes
            port:
              number: 8080