version: '3.3'
services:
  diabetes:
    image: diabetes
    restart: always
    ports:
      - '5001:5001'
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1024m'
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
      command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_turkish_ci', '--max_connections=650']
      ports:
        - '1001:3306'
      expose:
          - '3306'
      volumes:
          - mysql-volume:/var/lib/mysql
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: '3096m'
volumes:
 mysql-volume: