apiVersion: v1
kind: Pod
metadata:
  name: diabetespod
  labels:
    name: diabetes
    app: diabetes
spec:
  containers:
  - name: diabetes
    image: buketbm/diabetes
    imagePullPolicy: IfNotPresent